let dataAsesor = [
  {
    nama: "Euis Komalawati",
    no_reg: "MET.000.001946 2019 ",
    email: "",
    // password: encrypt("asesor_euis"),
    nama_skema: "Public Relation Coordinator",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Citra Agnestia",
    no_reg: "MET.000.001947 2019",
    email: "",
    // password: encrypt("asesor_citra"),
    nama_skema: "Public Relation Coordinator",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Poppie Indriyanti",
    no_reg: "MET.000.001948 2019",
    email: "",
    // password: encrypt("asesor_poppie"),
    nama_skema: "Public Relation Coordinator",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Nadiah Abidin",
    no_reg: "MET.000.000061 2023",
    email: "",
    // password: encrypt("asesor_nadiah"),
    nama_skema: "Media Planing Manager",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Ovi Olivia Belida",
    no_reg: "MET.000.000062 2023 ",
    email: "",
    // password: encrypt("asesor_ovi"),
    nama_skema: "Assisten Produser Program TV",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Saktisyahputra",
    no_reg: "MET.000.000063 2023 ",
    email: "",
    // password: encrypt("asesor_sakti"),
    nama_skema: "Media Planing Manager",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Heni Pridia RS",
    no_reg: "MET.000.000064 2023",
    email: "",
    // password: encrypt("asesor_heni"),
    nama_skema: "Front Office Supervisor",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Rustini",
    no_reg: "MET.000.000065 2023",
    email: "",
    // password: encrypt("asesor_rustini"),
    nama_skema: "Front Office Supervisor",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    nama: "Degdo Suprayitno",
    no_reg: "MET.000.000067 2023",
    email: "",
    // password: encrypt("asesor_degdo"),
    nama_skema: "Pengelolaan Pergudangan",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Sukarni Novita Sari",
    no_reg: "MET.000.000068 2023",
    email: "",
    // password: encrypt("asesor_sukarni"),
    nama_skema: "Manager Logistik Proyek",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Yusup Rachmat Hidayat",
    no_reg: "MET.000.001945 2019",
    email: "",
    // password: encrypt("asesor_yusup"),
    nama_skema: "Manager Logistik Proyek",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Dedy Kusna Utama",
    no_reg: "MET.000.000069 2023",
    email: "",
    // password: encrypt("asesor_dedy"),
    nama_skema: "Analis Kebijakan Publik",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Raden Kusyeni",
    no_reg: "MET.000.000070 2023",
    email: "",
    // password: encrypt("asesor_raden"),
    nama_skema: "Analis Kebijakan Publik",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Dwikora Harjo",
    no_reg: "MET.000.000071 2023",
    email: "",
    // password: encrypt("asesor_dwikora"),
    nama_skema: "Teknik Perpajakan PPh Badan Sektor Usaha dan Pergudangan",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Roike Tambengi",
    no_reg: "MET.000.001951 2019",
    email: "",
    // password: encrypt("asesor_roike"),
    nama_skema: "Teknik Perpajakan PPh Badan Sektor Usaha dan Pergudangan",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Rahadi Pratomo Singgih",
    no_reg: "MET.000.001953 2019",
    email: "",
    // password: encrypt("asesor_rahadi"),
    nama_skema: "Teknik Perpajakan PPh Badan Sektor Usaha dan Pergudangan",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Notika Rahmi",
    no_reg: "MET.000.001954 2019",
    email: "",
    // password: encrypt("asesor_notika"),
    nama_skema: "Teknik Perpajakan PPh Badan Sektor Usaha dan Pergudangan",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Agus Subagiyo",
    no_reg: "MET.000.000072 2023",
    email: "",
    // password: encrypt("asesor_agus"),
    nama_skema: "Teknik Perpajakan PPh Badan Sektor Usaha dan Pergudangan",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    nama: "Teguh Santoso",
    no_reg: "MET.000.000073 2023",
    email: "",
    // password: encrypt("asesor_teguh"),
    nama_skema: "Kewirausahaan Industri SKKNI L. 5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Widi Mulyadi",
    no_reg: "MET.000.001959 2019",
    email: "",
    // password: encrypt("asesor_widi"),
    nama_skema: "Kewirausahaan Industri SKKNI Level V",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Juardi",
    no_reg: "MET.000.000074 2023",
    email: "",
    // password: encrypt("asesor_juardi"),
    nama_skema: "Kewirausahaan Industri SKKNI Level V",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Achsanul Nashir",
    no_reg: "MET.000.001962 2019",
    email: "",
    // password: encrypt("asesor_achsanul"),
    nama_skema: "Penyelia Export",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    nama: "Abdul Gofur",
    no_reg: "MET.000.000075 2023",
    email: "",
    // password: encrypt("asesor_abdul"),
    nama_skema: "Penyelia Export",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
module.exports = dataAsesor;
